### PR TITLE
Caption on image

### PR DESCRIPTION
**Pull request by steveyblam**
Adds caption to image and supporting tests

### CODE REVIEW

**Comment by davidfloegel** [comment]
Caption is already an atom defined in typgraphy and should match what you have defined. If not, speak to Alex because there shouldn’t be any text used that isn’t defined in typography. 

The image itself should stay an atom

This should then also become a molecule.

**Comment by steveyblam** [comment]
> Caption is already an atom defined in typgraphy and should match what you have defined. If not, speak to Alex because there shouldn’t be any text used that isn’t defined in typography.
> 
> The image itself should stay an atom
> 
> This should then also become a molecule.

You're only holiday!!

**Comment by davidfloegel** [comment]
# GitHub Pages Deployment
Pull Request:
https://sofarsounds.github.io/maestro/pull/113
Branch:
https://sofarsounds.github.io/maestro/branches/caption_on_image
Storybook:
https://sofarsounds.github.io/maestro/b5356d11ed6cad96fba53376de8cec1ed9a3eb5c/
Build:
https://sofarsounds.github.io/maestro/b5356d11ed6cad96fba53376de8cec1ed9a3eb5c/dist.zip

**Comment by davidfloegel** [comment]
# GitHub Pages Deployment
Pull Request:
https://sofarsounds.github.io/maestro/pull/113
Branch:
https://sofarsounds.github.io/maestro/branches/caption_on_image
Storybook:
https://sofarsounds.github.io/maestro/89d92d5f7af1aff33aef52f10c41262957707932/
Build:
https://sofarsounds.github.io/maestro/89d92d5f7af1aff33aef52f10c41262957707932/dist.zip

**Pull request merged**
