### PR TITLE
Fixes! :)

### PR DESCRIPTION
**Pull request by davidfloegel**

### CODE REVIEW

**Comment by adaam2** [comment]
# GitHub Pages Deployment
Pull Request:
https://sofarsounds.github.io/maestro/pull/51
Branch:
https://sofarsounds.github.io/maestro/branches/uikit-fixes
Storybook:
https://sofarsounds.github.io/maestro/971fd903aee5d755b90bfff50788b6bf8759f4e9/
Build:
https://sofarsounds.github.io/maestro/971fd903aee5d755b90bfff50788b6bf8759f4e9/dist.zip

**Comment by adaam2** [comment]
# GitHub Pages Deployment
Pull Request:
https://sofarsounds.github.io/maestro/pull/51
Branch:
https://sofarsounds.github.io/maestro/branches/uikit-fixes
Storybook:
https://sofarsounds.github.io/maestro/ec7a00981fba0bfdb6eee6565f55a07e80f01b60/
Build:
https://sofarsounds.github.io/maestro/ec7a00981fba0bfdb6eee6565f55a07e80f01b60/dist.zip

**Comment by adaam2** [comment]
# GitHub Pages Deployment
Pull Request:
https://sofarsounds.github.io/maestro/pull/51
Branch:
https://sofarsounds.github.io/maestro/branches/uikit-fixes
Storybook:
https://sofarsounds.github.io/maestro/04b4358c1acddf34039282fabbef379e8518c05f/
Build:
https://sofarsounds.github.io/maestro/04b4358c1acddf34039282fabbef379e8518c05f/dist.zip

**Comment by davidfloegel** [comment]
# GitHub Pages Deployment
Pull Request:
https://sofarsounds.github.io/maestro/pull/51
Branch:
https://sofarsounds.github.io/maestro/branches/uikit-fixes
Storybook:
https://sofarsounds.github.io/maestro/04b4358c1acddf34039282fabbef379e8518c05f/
Build:
https://sofarsounds.github.io/maestro/04b4358c1acddf34039282fabbef379e8518c05f/dist.zip

**Pull request merged**
