### PR TITLE
More Docs :)

### PR DESCRIPTION
**Pull request by davidfloegel**

### CODE REVIEW

**Comment by davidfloegel** [comment]
# GitHub Pages Deployment
Pull Request:
https://sofarsounds.github.io/maestro/pull/148
Branch:
https://sofarsounds.github.io/maestro/branches/docs-2
Storybook:
https://sofarsounds.github.io/maestro/f11a77dc598ba9d6bd683d92f72a2973f1862de6/
Build:
https://sofarsounds.github.io/maestro/f11a77dc598ba9d6bd683d92f72a2973f1862de6/dist.zip

**Comment by adaam2** [comment]
Doing the Lord's work @davidfloegel 🙏

**Comment by davidfloegel** [comment]
> Doing the Lord's work @davidfloegel 🙏

Well no one else is doing it innit @adaam2 😂 Dan doesn't even know what documentation means @liondedan

**Comment by davidfloegel** [comment]
# GitHub Pages Deployment
Pull Request:
https://sofarsounds.github.io/maestro/pull/148
Branch:
https://sofarsounds.github.io/maestro/branches/docs-2
Storybook:
https://sofarsounds.github.io/maestro/fa6f7f8e5bc1440c31ce7f0dc158b93b83af95e5/
Build:
https://sofarsounds.github.io/maestro/fa6f7f8e5bc1440c31ce7f0dc158b93b83af95e5/dist.zip

**Pull request merged**
